apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocktail-manager-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cocktail-manager-auth
  template:
    metadata:
      labels:
        app: cocktail-manager-auth
    spec:
      containers:
        - name: cocktail-manager-auth
          image: us-central1-docker.pkg.dev/cocktailmanager/cocktail-manager-auth/cocktail-manager-auth:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-auth-secret
                  key: DATABASE_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-auth-secret
                  key: JWT_KEY
            - name: BDD_USER
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-auth-secret
                  key: BDD_USER
            - name: BDD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-auth-secret
                  key: BDD_PASSWORD
            - name: BDD_NAME
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-auth-secret
                  key: BDD_NAME
          resources:
            limits:
              memory: '2Gi'
              cpu: '3'
            requests:
              memory: '512Mi'
              cpu: '0.5'
---
apiVersion: v1
kind: Service
metadata:
  name: cocktail-manager-auth-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: cocktail-manager-auth
